add_event:
  name: Add event
  description: Add a refuel or maintenance event to a vehicle
  fields:
    vehicle:
      name: Vehicle
      description: Name of the vehicle
      required: true
      selector:
        text:
    event_type:
      name: Event type
      description: Type of event (refuel or maintenance)
      required: true
      selector:
        select:
          options:
            - "refuel"
            - "maintenance"
    date:
      name: Date
      description: Date of the event
      required: true
      selector:
        date:
    kilometers:
      name: Kilometers
      description: Current kilometers
      required: true
      selector:
        number:
          min: 0
          step: 1
    notes:
      name: Notes
      description: Optional notes
      required: false
      selector:
        text:
    liters:
      name: Liters
      description: Liters of fuel (for refuel events)
      required: false
      selector:
        number:
          min: 0
          step: 0.1
    price_per_liter:
      name: Price per liter
      description: Price per liter (for refuel events)
      required: false
      selector:
        number:
          min: 0
          step: 0.01
    maintenance_type:
      name: Maintenance type
      description: Type of maintenance (for maintenance events)
      required: false
      selector:
        text:
    cost:
      name: Cost
      description: Cost of maintenance (for maintenance events)
      required: false
      selector:
        number:
          min: 0
          step: 0.01
