add_event:
  name: Ajouter un événement
  description: Ajouter un événement (plein ou entretien) à un véhicule
  fields:
    vehicle:
      name: Véhicule
      description: Nom du véhicule
      required: true
      selector:
        text:
    event_type:
      name: Type d'événement
      description: Type d'événement (plein ou entretien)
      required: true
      selector:
        select:
          options:
            - "refuel"
            - "maintenance"
    date:
      name: Date
      description: Date de l'événement
      required: true
      selector:
        date:
    kilometers:
      name: Kilométrage
      description: Kilométrage actuel
      required: true
      selector:
        number:
          min: 0
          step: 1
    notes:
      name: Notes
      description: Notes optionnelles
      required: false
      selector:
        text:
    liters:
      name: Litres
      description: Litres de carburant (pour les pleins)
      required: false
      selector:
        number:
          min: 0
          step: 0.1
    price_per_liter:
      name: Prix au litre
      description: Prix au litre (pour les pleins)
      required: false
      selector:
        number:
          min: 0
          step: 0.01
    maintenance_type:
      name: Type d'entretien
      description: Type d'entretien (pour les entretiens)
      required: false
      selector:
        text:
    cost:
      name: Coût
      description: Coût de l'entretien (pour les entretiens)
      required: false
      selector:
        number:
          min: 0
          step: 0.01
