enregistrer_evenement:
  description: "Enregistre un plein ou un entretien pour une voiture"
  fields:
    type:
      description: "Type d'événement : Plein ou Entretien"
      example: "Plein"
    voiture_id:
      description: "Identifiant de la voiture"
      example: "audi_a3"
    km:
      description: "Kilométrage"
      example: 55000
    litres:
      description: "Litres pour un plein"
      example: 40
    prix_litre:
      description: "Prix par litre"
      example: 1.60
    prix_entretien:
      description: "Prix entretien"
      example: 120
    note:
      description: "Notes éventuelles"
      example: "Vidange huile"
